backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

locale: pt

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
